spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ruoyi_vue_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wjy123321
    driver-class-name: com.mysql.jdbc.Driver